language: c

os:
    - linux
    - windows
    - osx

compiler:
    - gcc
    - clang

stages:
    - build

script:
    - cmake
        -B ${TRAVIS_BUILD_DIR}/build
        -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install
        .
    - cmake
        --build ${TRAVIS_BUILD_DIR}/build
        --target install
